export const VEHICLE_OPTIONS = [
  "Climatisation",
  "Climatisation automatique",
  "GPS / Navigation",
  "Caméra de recul",
  "Radar de recul",
  "Régulateur de vitesse",
  "Régulateur adaptatif",
  "Jantes alliage",
  "Toit ouvrant",
  "Sièges cuir",
  "Sièges chauffants",
  "Bluetooth",
  "Apple CarPlay / Android Auto",
  "Attelage",
  "Vitres électriques",
  "Rétroviseurs électriques",
  "Aide au stationnement",
  "Démarrage sans clé",
  "Phares LED",
  "Détecteur d'angle mort",
] as const;
